app/src/main/res/values/colors.xml
=> Init colors.xml

app/src/main/AndroidManifest.xml, app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/res/layout/activity_root.xml
Создал пустые gitkeep для создания пакетов, при создании классов в пакетах gitkeep следует удалить
=> Init structure of project

app/src/main/java/ru/practicum/android/diploma/team/ui/TeamFragment.kt, app/src/main/res/layout/fragment_team.xml, app/src/main/res/values/dimens.xml
когда будут готовы стили, нужно будет поправить цвета
=> Верстка экрана "Команда" 

app/src/main/java/ru/practicum/android/diploma/details/ui/DetailsFragment.kt, app/src/main/java/ru/practicum/android/diploma/favorite/ui/FavoritesFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/CountryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/FiltrationFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/PlaceOfWorkFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/RegionFragment.kt, app/src/main/java/ru/practicum/android/diploma/main_search/ui/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt, app/src/main/res/layout/activity_root.xml, app/src/main/res/layout/fragment_country.xml, app/src/main/res/layout/fragment_details.xml, app/src/main/res/layout/fragment_favorites.xml, app/src/main/res/layout/fragment_filtration.xml, app/src/main/res/layout/fragment_place_of_work.xml, app/src/main/res/layout/fragment_region.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
созданы заглушки фрагментов, граф навигации.
=> Diploma#14

app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/res/layout/activity_root.xml, app/src/main/res/layout/fragment_favorites.xml, app/src/main/res/menu/bottom_navigation_menu.xml, app/src/main/res/navigation/navigation_graph.xml
Верстку нужно подправить, Но сначала нужно стянуть темы. Создала себе задачку.
=> Реализованы переходы с помощью navigationGraph

app/src/main/res/drawable/shape_search_field_background.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml, app/src/main/res/values/themes.xml
Fix dimens.xml,strings,fragment_search.xml
=> Init style.xml,theme

app/src/main/res/layout/fragment_favorites.xml, app/src/main/res/values/style.xml
=> Diploma#31

app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
=> StatusBarColor

app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/favorite/data/impl/VacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/api/VacancyInteractor.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/api/VacancyRepository.kt, app/src/main/java/ru/practicum/android/diploma/favorite/domain/impl/VacancyInteractorImpl.kt
=> Diploma#67

app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt
=> Diploma#69

app/src/androidTest/java/ru/practicum/android/diploma/PluralsTest.kt
=> Diploma#71

app/src/main/java/ru/practicum/android/diploma/search/ui/SearchVacancyAdapter.kt
Добавить функцию addItemsInRecycler в адаптере ресайклера, заменить vacancyList адаптера на mutableListOf<SimpleVacancy>
=> Diploma#91

app/src/main/res/layout/fragment_favorites.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_team.xml
Заголовки Избранное, Команда toolbar
=> Diploma#89

app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
=> Diploma#95

app/src/main/java/ru/practicum/android/diploma/search/ui/SearchVacancyViewHolder.kt, app/src/main/java/ru/practicum/android/diploma/util/DimensionUtils.kt, app/src/main/res/layout/item_vacancy.xml
Сделать Итем ресайклера без cardView, просто ImageView.
Установить во вьюхолдер закругления в глайде, если есть на макете.
=> Diploma#96

app/src/main/res/drawable/icon_favorites.xml, app/src/main/res/drawable/icon_favorites_off.xml, app/src/main/res/drawable/icon_favorites_on.xml, app/src/main/res/drawable/shape_employer_background.xml, app/src/main/res/layout/fragment_details_vacancy.xml, app/src/main/res/values/dimens.xml
Экран деталей вакансии готов.
Сопутствующие ресурсы добавлены в проект.
**Необходимо внести изменения в будущем:**
=> Diploma#106: Реализовал вёрстку экрана деталей вакансии.

app/src/main/java/ru/practicum/android/diploma/details/ui/VacancyDetailsFragment.kt, app/src/main/res/drawable/icon_back.xml, app/src/main/res/layout/fragment_details_vacancy.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml
=> Diploma#109

app/src/main/res/values/style.xml
=> Diploma#111

app/src/main/java/ru/practicum/android/diploma/search/ui/SearchVacancyViewHolder.kt, app/src/main/res/values/strings.xml
Реализовать корректное отображение зарплаты
=> Diploma#113

app/src/main/java/ru/practicum/android/diploma/search/data/impl/SearchRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/model/SimpleVacancy.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt, app/src/main/res/values/strings.xml
Количество вакансий, но отображается 20(текущих на странице)
=> Diploma#116

app/src/main/java/ru/practicum/android/diploma/filter/ui/FiltrationFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/PlaceOfWorkFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt, app/src/main/res/drawable/icon_arrow_forward.xml, app/src/main/res/drawable/shape_filtration_background.xml, app/src/main/res/layout/fragment_filtration.xml, app/src/main/res/layout/fragment_place_of_work.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/style.xml
Вёрстка фрагмента настройки фильтрации
Вёрстка фрагмента выбора места работы
=> Diploma#126

app/src/main/res/drawable/text_input_box_stroke.xml, app/src/main/res/layout/fragment_filtration.xml, app/src/main/res/layout/fragment_industry.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/style.xml
Diploma#161
Diploma#163
Выправил кнопку цвета и эдит текст в "Настройке фильтрации"
=> Diploma#161

app/src/main/java/ru/practicum/android/diploma/Currency.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchVacancyViewHolder.kt
Поправил отображение валюты и символ
=> Diploma#176

app/src/main/java/ru/practicum/android/diploma/filter/ui/industry/IndustryAdapter.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/industry/IndustryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/industry/IndustyViewHolder.kt
Выбирается только один фрагмент, кнопка выбрать появляется и отрабатывает правильно
=> Radiocheck

app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
=> Spacebar download

app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt, app/src/main/res/values/strings.xml
=> String connection

app/src/main/java/ru/practicum/android/diploma/convertor/DbConverter.kt, app/src/main/java/ru/practicum/android/diploma/details/data/dto/SearchDetailsResponse.kt, app/src/main/java/ru/practicum/android/diploma/details/data/impl/SearchDetailsRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/details/data/model/Area.kt, app/src/main/java/ru/practicum/android/diploma/details/domain/model/Vacancy.kt, app/src/main/java/ru/practicum/android/diploma/details/ui/VacancyDetailsFragment.kt, app/src/main/java/ru/practicum/android/diploma/favorite/data/db/AppDatabase.kt, app/src/main/java/ru/practicum/android/diploma/favorite/data/db/FavoriteVacancyEntity.kt
Добавил Area в которой забирается регион, добавил выбор если отсутствует адрес, то регион.
В адресе теперь получаем не CITY, а RAW целиковый адрес, город, дом, номер
=> AreaAdress

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/filter/data/impl/FiltrationRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/filter/presentation/FiltrationViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filter/presentation/model/FilterSearch.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/FiltrationFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/country/CountryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/industry/IndustryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/region/RegionFragment.kt, app/src/main/java/ru/practicum/android/diploma/filter/ui/workplace/PlaceOfWorkFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values/strings.xml
=> Diploma#246:
